version: '3.5'

services:
  postgres:
    image: postgres:14.3
    environment:
      POSTGRES_USER: excellocal
      POSTGRES_PASSWORD: password
      POSTGRES_DB: excellocal
      TZ: "Asia/Tokyo"
    ports:
      - "15432:5432"
    healthcheck:
      test: pg_isready -U excellocal -d excellocal
      timeout: 45s
      interval: 10s
      retries: 10
    volumes:
      - ./testdata/schema:/docker-entrypoint-initdb.d

  devcontainer:
    image: golang:1.19-bullseye
    working_dir: /workspace
    volumes:
      - .:/workspace:cached
    command: sleep infinity
    restart: "no"
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      EXCELTESTING_CONNECTION: "postgres://excellocal:password@postgres:5432/excellocal?sslmode=disable"
